version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DEPLOY_DB_PASS}
      MYSQL_DATABASE: ccmake
      MYSQL_USER: ${DEPLOY_DB_USER}
      MYSQL_PASSWORD: ${DEPLOY_DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend-network

  spring-app:
    build: .
    container_name: spring-app-container
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${DEPLOY_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DEPLOY_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEPLOY_DB_PASS}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: deploy
      JWT_SECRET: ${DEPLOY_JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
